#!/usr/bin/env python
# -*- coding: utf-8 -*-
import xml.etree.cElementTree as ET
import pprint
import re
"""
determines unique users which have contributed to the map.
"""

def get_user(element):
    return


def process_map(filename):
    users = set()
    for _, element in ET.iterparse(filename):
        if element.get('user'):
            users.add(element.get('user'))

    return users


users = process_map('albuquerque_new-mexico.osm')
print len(users)
pprint.pprint(users)

""" OUTPUT

438
set(['25or6to4',
     '42429',
     'ABQBitcoins',
     'AMY-jin',
     'AaronAsAChimp',
     'Ahlzen',
     'AndiG88',
     'Andrew Fish',
     'AndrewSnow',
     'AndyAyre',
     'ArtiePenguin1',
     'AtlAtl',
     'B B',
     'BBPratt',
     'BCNorwich',
     'BTO',
     'BenCook',
     'Biff',
     'Boardergrl',
     'Bonusdays',
     'Brian Thompson2',
     'Bryce C Nesbitt',
     'Bullroarer',
     'California Bear',
     'CalliBrown',
     'Carl Simonson',
     'Catherine Page Harris',
     'Cato_d_Ae',
     'Cerritus',
     'Chetan_Gowda',
     'Chris Filip',
     'Chris1216',
     'ChrisZontine',
     'ChrissW-R1',
     'Cicerone',
     'Claudius Henrichs',
     'Czmartin',
     'DLichti',
     'DSmall',
     'Dafmaster',
     'Dami_Tn',
     'Damien F',
     'Dan Morgan',
     'DanHomerick',
     'DaveHansenTiger',
     'David & Christine Schmitt',
     'Davio',
     'DennisL',
     'Dion Dock',
     'Dorene Kuffer',
     'DougD505',
     'Dr Kludge',
     'DrSeuthberg',
     'Drizzle',
     'Dustin Harvey',
     'EMS-DRS',
     'EMccutchan',
     'Echo Echo',
     u'Eckhart W\xf6rner',
     'EdHillsman',
     'Edward',
     'Eric Godwin',
     'FTA',
     'FahRadler',
     'FootPrintsHC',
     'FranziT',
     'FrozenFlame22',
     'FvGordon',
     'GPS_dr',
     'Geoff Reedy',
     'Geogast',
     'Geospizinae',
     'GerdP',
     'Glassman',
     'Gnattang',
     'Harry Wood',
     'Hjart',
     'Hobgoblin',
     'HolgerJeromin',
     'HuntWorks',
     'InsertUser',
     'Iowa Kid',
     'J B Crawford',
     'JaggedMind',
     'Jake Strine',
     'Jano John Akim Franke',
     'Jbeltran505',
     'Jeff Ollie',
     'Jemez792',
     'JessAk71',
     'JimmyRocks',
     'Joe from Albuquerque',
     'Jonathan ZHAO',
     'Josef73',
     'KaleenaSawyer',
     'Katei',
     'KristenK',
     'Kylie Elizabeth',
     u'La Chaussi\xe9re',
     'Lambertus',
     'Latze',
     'Lefty256',
     'Little Brother',
     'LoriLaw',
     'Lucas Marques',
     'Luis36995',
     'MacDaddy1660B',
     'Manu1400',
     'Map King',
     'Mark_S',
     'Marsden',
     'Maskulinum',
     'Matt Carus',
     'MattGrommes',
     'MatthieuMartin',
     'Mcooper',
     'Md Alamgir',
     'Med',
     'MikeN',
     'Mindless',
     'Mirko',
     'NE2',
     'NE3',
     'NMAppraiser',
     'NMoore',
     'NZGraham',
     'NayanataraM',
     'Netzwolf',
     'NickOpenMap',
     'OMapper',
     'OPerivar',
     'OSMF Redaction Account',
     'Omnific',
     'PHerison',
     'Paul Johnson',
     'PaulCrickard',
     'Pauline_cnm',
     'Pedro L Gonzalez',
     'Peter14',
     'Phil Scherer',
     'Photo Booth Rentals of New Mexico',
     'PlaneMad',
     'Pmz',
     'Polarbear',
     'Polarbear-repair',
     'Quelab Hackerspace',
     'R Pasekoff',
     'R0bst3r',
     'RU1NER988',
     'RYT',
     'Redaragorn',
     'ReinerMeyer',
     'RetiredInNH',
     'RichRico',
     'Rincewind7',
     'RoadGeek_MD99',
     'Rockear',
     u'Rodolphe Qui\xe9deville',
     'Ropino',
     'Rovastar',
     'Rub21',
     'Rudolf Mayer',
     'RussInAbq',
     'Russbiggs',
     'SK53',
     'SRoss',
     'SamatJain',
     'Samusz',
     'Sanderd17',
     'SaraLynnOsk',
     'Sarr_Cat',
     'ScottHolswade',
     'Shmias',
     'Skagen',
     'Smithra2',
     'SomeoneElse_Revert',
     'Sparks',
     'Stemby',
     'Steve',
     'SteveDorries',
     'SveLil',
     'Syl',
     'TIGERcnl',
     'Taka',
     'Taylor Blueher',
     'Test360',
     'TheDutchMan13',
     'TheHammer',
     'Thekster93',
     'Thomas8122',
     'Tim Baggett',
     'Tim Litwiller',
     'Tim_the_toolman',
     'Timothy Smith',
     'TinaUNM',
     'ToeBee',
     'Tom Chance',
     'TomHynes',
     'Tom_Holland',
     'TomasB',
     'TonyDavis',
     'TonyMa',
     'TorCguy',
     'Tordanik',
     'TorhamZed',
     'Tronikon',
     u'Walter Schl\xf6gl',
     'Warhobbit',
     'WebforMichael',
     'WebforSara',
     'WernerP',
     'WingedStone',
     'Wolfram Sobotta',
     'YannC',
     'Your Village Maps',
     'ZZ29',
     'Zanderschiff',
     'abel801',
     'aceman444',
     'achims311',
     'adamos',
     'afdreher',
     'amallen',
     'amg83',
     'amillar',
     'amyb',
     'anchornm',
     'andrewpmk',
     'andygol',
     'anjbe',
     'anttiklemm',
     'ashizam',
     'askewchan',
     'austi1996',
     'avlasic',
     'baditaflorin',
     'badpap',
     'baerental',
     'balrog-kun',
     'barrycarter',
     'bbethge',
     'bck',
     'bdiscoe',
     'bdon',
     'bertboy',
     'beweta',
     'bondah',
     'bot-mode',
     'brianegge',
     'brogo',
     'bullmap',
     'calfarome',
     'carmijo',
     'cbkiyanda',
     'cgu66',
     'cluening',
     'crachau',
     'cseely',
     'cyprusglobe',
     'damfino1920',
     'danaM',
     'dannykath',
     'davidearl',
     'dbaron',
     'dchiles',
     'dcs',
     'derricknehrenberg',
     'dima',
     'doj',
     'ebrelsford',
     'ediyes',
     'egore911',
     'elbatrop',
     'emacsen',
     'eric22',
     'erjiang',
     'escada',
     'ezdaddy',
     'fbasker',
     'felfri',
     'fredjunod',
     'freethebicyclists',
     'fx99',
     'gengnom',
     'geochrome',
     'geodreieck4711',
     'geomenke',
     'geowas',
     'gileri',
     'gormo',
     'gormur',
     'gpsradler',
     'greenv505',
     'grossing',
     'gwerito',
     'h4ck3rm1k3',
     'happy5214',
     'hawoni',
     'hca',
     'hdtravel',
     'highflyer74',
     'hno2',
     'hobbesvsboyle',
     'hofoen',
     'homeslice60148',
     'iandees',
     'iantk',
     'inositle',
     'ipodolsk',
     'isabellekh',
     'ivyjen',
     'j3d',
     'jaboyce',
     'jackbus',
     'jacobbraeutigam',
     'jaimemd',
     'jameshands',
     'jgpacker',
     'jimlinux',
     'jlaue',
     'jonaskmt',
     'jonesydesign',
     'jotzt',
     'jpnoe72',
     'jumbanho',
     'jwass',
     'kaervek',
     'karitotp',
     'kasatch',
     'keinseier',
     'keyalea',
     'kisaa',
     'klusark',
     'kn2m',
     'kr4z33',
     'kriscarle',
     'kugelfiesch',
     'lb17084',
     'lesko987',
     'maggot27',
     'mapper999',
     'mappy123',
     'mapsinE3',
     'marook',
     'matthieun',
     'maxerickson',
     'maxolasersquad',
     'mexico_boundaries_import',
     'mey2008',
     'mgmcc',
     'mgoe',
     'mhusseini',
     'michael colvin',
     'mjulius',
     'moren',
     'mregan',
     'mvexel',
     'mwra-uk',
     'n76',
     'nathancallaghan',
     'ncountrygirl',
     'neufeind',
     'neuhausr',
     'nfgusedautoparts',
     'nikhilprabhakar',
     'ninja9878',
     'oini',
     'okilimu',
     'oldenburg69',
     'oldtopos',
     'osmlurker',
     'paulmach',
     'polarsleuth',
     'poppei82',
     'pratikyadav',
     'rad1ance',
     'ramyaragupathy',
     'richrdk',
     'rickmastfan67',
     'rlogan121',
     'robertstack',
     'robgeb',
     'rolandg',
     'ruph',
     'ruthmaben',
     'rw_',
     'rw__',
     'ryanbranciforte',
     'ryangrebe',
     'sabas88',
     'salix01',
     'samely',
     'scott a',
     'scruss',
     'sdiddy',
     'seattlefyi',
     'shravan91',
     'shvrm',
     'sikelianos',
     'skorasaurus',
     'skquinn',
     'sleepcamel',
     'smallwolf',
     'somehow_different',
     'srividya_c',
     'stangoodman',
     'stevea',
     'stucki1',
     't-i',
     'techlady',
     'telenav66',
     'theonlytruth',
     'therockster',
     'tkzoey',
     'trailuser79',
     'tsuhre',
     'tunnelbauer',
     'uboot',
     'user_2985937',
     'user_5359',
     'van Rees',
     'volite',
     'vonvonvon',
     'voschix',
     'wambacher',
     'wiwaxia',
     'wjl',
     'wmann',
     'woodpeck_fixbot',
     'woodpeck_repair',
     'wvdp',
     'xybot',
     'ypid',
     'zacmccormick',
     'zbinger',
     'zehpunktbarron',
     'zephyr',
     'zeromap'])
"""